title: 曰困固
author: 范冰冰
email: 范冰冰@Qingdao.com
description: > # I got broads in Atlanta
  Twistin' dope, lean, and the Fanta
  Credit cards and the scammers
  Hittin' off licks in the bando

# social links
twitter_username: 范冰冰
github_username:  范冰冰

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
